### ISSUE TITLE
System.OutOfMemoryException in Release .exe

### ISSUE THREAD

**Issue by JesperKuipers** [danarrib/BigSQLRunner#1]
Even tho your program is aimed to stop this from happening it still does. The .sql file is 160GB btw. 

Do you know a way to solve this?

![image](https://user-images.githubusercontent.com/44586411/109810569-fcb29f00-7c29-11eb-9b4a-1ea8e0cbdd04.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at BigSQLRunnerUI.frmMainUI.RunScript(String sourceScript, String connectionString, Int16 qtyMaxLines, Int64 startLine)
   at BigSQLRunnerUI.frmMainUI.btnRunScript_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BigSQLRunnerUI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/jespe/Downloads/BigSQLRunner.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by JesperKuipers** [comment]
@danarrib  the program is running 32 bit which caps at 2GB of ram, is there any way you could make it 64-bit?

**Comment by danarrib** [comment]
It's not supposed to crash. I personally ran 2TB files with it.

But maybe your problem is that a single line is larger than 2 GB... In this case I would recommend you to make your script in such way that each line doesn't get this large.

Anyway, I built a new version for x64.
https://github.com/danarrib/BigSQLRunner/releases/tag/v1.1

Let me know if it solves your problem.

**Comment by JesperKuipers** [comment]
@danarrib  ye I'm running the source code in visual studio with debug on x68 which works for me. It wasn't a single line that crashed it for me but it peaked randomly to 2.3GB. But now on 64-bit, it runs on 5 out of my 32GB ram which works fine for me.

**Comment by JesperKuipers** [comment]
Would also love a way to disable the .error file, cause my DB is so big that my SSD gets full. Work around right now is to stop just before the disk gets full and then restart from the line number.

**Comment by JesperKuipers** [comment]
This may sound stupid but I can't find the database. 

These are the databases I have after importing the DB:
![image](https://user-images.githubusercontent.com/44586411/109870486-71a5c900-7c6a-11eb-9f5d-5783a56d51b3.png)

I used my connect string before for the other databases before, ur test even tells me it's working: 
```
Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False```

**Comment by danarrib** [comment]
Ok, I added the option to not log the errors.

![image](https://user-images.githubusercontent.com/17026744/109876781-eec44480-7c50-11eb-8a55-6b69846da2a8.png)
Just uncheck the "Log errors" checkbox.

https://github.com/danarrib/BigSQLRunner/releases/tag/v.1.1.1

**Comment by danarrib** [comment]
> This may sound stupid but I can't find the database.
> 
> 
> I used my connect string before for the other databases before, ur test even tells me it's working:
> 
> ```
> Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False```
> ```

Looks like your connection string is pointing to the master database... So probably your script ran over master.

**Comment by JesperKuipers** [comment]
Ah, I found the issue, its a MySQL DB so need to convert it first.
